/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientClient_idRouteImport } from './routes/client.$client_id'
import { Route as CaseCase_idRouteImport } from './routes/case.$case_id'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClient_idRoute = ClientClient_idRouteImport.update({
  id: '/client/$client_id',
  path: '/client/$client_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseCase_idRoute = CaseCase_idRouteImport.update({
  id: '/case/$case_id',
  path: '/case/$case_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/case/$case_id': typeof CaseCase_idRoute
  '/client/$client_id': typeof ClientClient_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/case/$case_id': typeof CaseCase_idRoute
  '/client/$client_id': typeof ClientClient_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/case/$case_id': typeof CaseCase_idRoute
  '/client/$client_id': typeof ClientClient_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/feedbacks'
    | '/logs'
    | '/case/$case_id'
    | '/client/$client_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/feedbacks'
    | '/logs'
    | '/case/$case_id'
    | '/client/$client_id'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/feedbacks'
    | '/logs'
    | '/case/$case_id'
    | '/client/$client_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  FeedbacksRoute: typeof FeedbacksRoute
  LogsRoute: typeof LogsRoute
  CaseCase_idRoute: typeof CaseCase_idRoute
  ClientClient_idRoute: typeof ClientClient_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$client_id': {
      id: '/client/$client_id'
      path: '/client/$client_id'
      fullPath: '/client/$client_id'
      preLoaderRoute: typeof ClientClient_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$case_id': {
      id: '/case/$case_id'
      path: '/case/$case_id'
      fullPath: '/case/$case_id'
      preLoaderRoute: typeof CaseCase_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  FeedbacksRoute: FeedbacksRoute,
  LogsRoute: LogsRoute,
  CaseCase_idRoute: CaseCase_idRoute,
  ClientClient_idRoute: ClientClient_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
