/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as ClientsClient_idRouteImport } from './routes/clients/$client_id'
import { Route as CasesCase_idRouteImport } from './routes/cases/$case_id'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClient_idRoute = ClientsClient_idRouteImport.update({
  id: '/clients/$client_id',
  path: '/clients/$client_id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCase_idRoute = CasesCase_idRouteImport.update({
  id: '/cases/$case_id',
  path: '/cases/$case_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/cases/$case_id': typeof CasesCase_idRoute
  '/clients/$client_id': typeof ClientsClient_idRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/cases/$case_id': typeof CasesCase_idRoute
  '/clients/$client_id': typeof ClientsClient_idRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedbacks': typeof FeedbacksRoute
  '/logs': typeof LogsRoute
  '/cases/$case_id': typeof CasesCase_idRoute
  '/clients/$client_id': typeof ClientsClient_idRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedbacks'
    | '/logs'
    | '/cases/$case_id'
    | '/clients/$client_id'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedbacks'
    | '/logs'
    | '/cases/$case_id'
    | '/clients/$client_id'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/feedbacks'
    | '/logs'
    | '/cases/$case_id'
    | '/clients/$client_id'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbacksRoute: typeof FeedbacksRoute
  LogsRoute: typeof LogsRoute
  CasesCase_idRoute: typeof CasesCase_idRoute
  ClientsClient_idRoute: typeof ClientsClient_idRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$client_id': {
      id: '/clients/$client_id'
      path: '/clients/$client_id'
      fullPath: '/clients/$client_id'
      preLoaderRoute: typeof ClientsClient_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$case_id': {
      id: '/cases/$case_id'
      path: '/cases/$case_id'
      fullPath: '/cases/$case_id'
      preLoaderRoute: typeof CasesCase_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbacksRoute: FeedbacksRoute,
  LogsRoute: LogsRoute,
  CasesCase_idRoute: CasesCase_idRoute,
  ClientsClient_idRoute: ClientsClient_idRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
